#!/bin/bash
 2
 3 for line in $(sed -e '1d' data.csv); do { 
 4 a=$(echo $line | cut -d "," -f 2  | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
 4 b=$(sed -e '1d' data.csv | awk '{split($0,var,",");if ( length(var[1]) != 0 && ( length(var[2]) != 0 ) && (var[1] !~ /^[[:digit:]]{0,100}$/) ) { print var[1]"\t\tA\t"var[2];}}')
 5 if [ -z "$a" ] || [ -z "$b" ] ; then echo "fichier invalide"
 6         x="invalide"
 7         if [[ $x == "invalide" ]]; then exit 0
 8         fi
 9 else echo "fichier valide"
10         x="valide"
11         if [[ ! -e data.csv ]]; then {
12                 echo "le fichier data.csv n'existe pas"
13                 exit 1
14         }
15         fi
16         if  [[ $x == "valide" ]]; then
17                 echo $line | sed -e "s/,/\t\tA\t/" >> /var/named/recto.dns
18                 systemctl restart named
19         fi
20 fi
21 }
22 done
