#!/bin/bash
for line in $(sed -e '1d' /usr/share/machines.csv); do { 
	a=$(echo $line | awk '{split($0,var,",");if ( length(var[1]) != 0 && length(var[2]) != 0 ) { print "ligne complète";}}')
	b=$(echo $line | cut -d "," -f 2  | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
	if [ -z "$a" ] || [ -z "$b" ] ; then echo "ligne invalide"
		v="invalide"
		if [[ $v == "invalide" ]]; then exit 0
		fi
	else echo "ligne valide"
		v="valide"
		if [[ ! -e /usr/share/machines.csv ]]; then {
			echo "le fichier machines.csv n'existe pas dans /usr/share/"
			exit
		}
	fi
	if  [[ $v == "valide" ]]; then
		echo $line | sed -e "s/,/\tA\t/" >> /var/named/examen.zone
		systemctl restart named
	fi
fi
}
done
